ACTIVITIES = [
    {"id": "studying",        "label": "Studying",        "hint": "Calm, focused, minimal distraction."},
    {"id": "working_out",     "label": "Working Out",      "hint": "High energy, driving beats, pump-up."},
    {"id": "falling_in_love", "label": "Falling in Love",  "hint": "Warm, intimate, emotional."},
    {"id": "driving",         "label": "Driving",          "hint": "Steady rhythm, open feel, road-ready."},
    {"id": "meditating",      "label": "Meditating",       "hint": "Ambient, slow, spacious, gentle."},
    {"id": "partying",        "label": "Partying",         "hint": "Upbeat, loud, infectious groove."},
    {"id": "winding_down",    "label": "Winding Down",     "hint": "Soft, slow, relaxing, lullaby-like."},
]

ACTIVITY_SHIFTS = {
    "studying": {
        "tempo": "steady",
        "vocals": "none",
        "complexity": "low",
        "bass_weight": "low",
        "lyric_tone": "none",
        "rhythm_pattern": "steady-minimal",
        "arrangement": "sparse layers",
        "sonic_space": "tight, focused",
    },
    "working_out": {
        "tempo": "up",
        "vocals": "high",
        "complexity": "mid",
        "bass_weight": "heavy",
        "lyric_tone": "empowering",
        "rhythm_pattern": "driving four-on-floor",
        "arrangement": "stacked, layered",
        "sonic_space": "wide, stadium",
    },
    "falling_in_love": {
        "tempo": "steady",
        "vocals": "mid",
        "complexity": "mid",
        "bass_weight": "mid",
        "lyric_tone": "tender, intimate",
        "rhythm_pattern": "swaying",
        "arrangement": "lush strings and pads",
        "sonic_space": "close, intimate",
    },
    "driving": {
        "tempo": "mid",
        "vocals": "mid",
        "complexity": "mid",
        "bass_weight": "heavy",
        "lyric_tone": "confident",
        "rhythm_pattern": "groovy steady pulse",
        "arrangement": "bass-forward, open",
        "sonic_space": "panoramic, wide",
    },
    "meditating": {
        "tempo": "down",
        "vocals": "none",
        "complexity": "low",
        "bass_weight": "sub-bass only",
        "lyric_tone": "none",
        "rhythm_pattern": "freeform ambient",
        "arrangement": "minimal drones",
        "sonic_space": "vast, spacious",
    },
    "partying": {
        "tempo": "up",
        "vocals": "high",
        "complexity": "high",
        "bass_weight": "heavy",
        "lyric_tone": "hype, call-response",
        "rhythm_pattern": "four-on-floor bounce",
        "arrangement": "full-stack dance",
        "sonic_space": "loud, immersive",
    },
    "winding_down": {
        "tempo": "down",
        "vocals": "low",
        "complexity": "low",
        "bass_weight": "low",
        "lyric_tone": "tender, soothing",
        "rhythm_pattern": "slow lullaby",
        "arrangement": "gentle acoustic and pads",
        "sonic_space": "soft, cozy",
    },
}
