MOODS = [
    {"id": "chill", "label": "Chill", "hint": "Lower tempo, softer dynamics, smooth textures."},
    {"id": "happy", "label": "Happy", "hint": "Brighter harmony, upbeat groove, optimistic feel."},
    {"id": "energetic", "label": "Energetic", "hint": "Higher tempo, stronger transients, driving rhythm."},
    {"id": "sad", "label": "Sad", "hint": "Slower tempo, minor-leaning, simpler arrangement."},
    {"id": "focus", "label": "Focus", "hint": "Steady tempo, minimal vocals, low variation."},
    {"id": "romantic", "label": "Romantic", "hint": "Warm harmony, lush textures, mid-tempo."},
    {"id": "aggressive", "label": "Aggressive", "hint": "Harder drums, darker timbre, high intensity."},
]

MOOD_SHIFTS = {
    "chill": {
        "tempo": "down",
        "brightness": "down",
        "energy": "down",
        "bass_weight": "mid",
        "lyric_tone": "reflective",
        "harmonic_mode": "major-leaning",
        "texture": "smooth, warm",
        "dynamics": "gentle",
    },
    "happy": {
        "tempo": "up",
        "brightness": "up",
        "energy": "mid",
        "bass_weight": "mid",
        "lyric_tone": "uplifting",
        "harmonic_mode": "major",
        "texture": "bright, sparkling",
        "dynamics": "bouncy",
    },
    "energetic": {
        "tempo": "up",
        "brightness": "mid",
        "energy": "up",
        "bass_weight": "high",
        "lyric_tone": "empowering",
        "harmonic_mode": "major",
        "texture": "sharp, crisp",
        "dynamics": "punchy",
    },
    "sad": {
        "tempo": "down",
        "brightness": "down",
        "energy": "down",
        "bass_weight": "low",
        "lyric_tone": "melancholic",
        "harmonic_mode": "minor",
        "texture": "muted, soft",
        "dynamics": "sparse",
    },
    "focus": {
        "tempo": "steady",
        "brightness": "mid",
        "energy": "down",
        "bass_weight": "low",
        "lyric_tone": "none",
        "harmonic_mode": "neutral",
        "texture": "clean, minimal",
        "dynamics": "steady",
    },
    "romantic": {
        "tempo": "steady",
        "brightness": "mid",
        "energy": "mid",
        "bass_weight": "mid",
        "lyric_tone": "tender",
        "harmonic_mode": "major-minor blend",
        "texture": "lush, warm",
        "dynamics": "swelling",
    },
    "aggressive": {
        "tempo": "up",
        "brightness": "down",
        "energy": "up",
        "bass_weight": "heavy",
        "lyric_tone": "defiant",
        "harmonic_mode": "minor, dissonant",
        "texture": "distorted, raw",
        "dynamics": "explosive",
    },
}
